version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-dev
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "DinStærkeKode123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - devnet

volumes:
  mssql_data:

networks:
  devnet:
    driver: bridge
